import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextNProgress from "next-nprogress-bar";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import ProgressBar from "./components/Progress/ProgressBar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider className='clerkp'>
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ProgressBar/>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
