import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "../components/allblogs/NavBar";
import Filter from "../components/categories/Filter";
import {
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import Footer from "../components/Footer/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <div>
        <NavBar/>
        <Filter/>
        {children}
        <Footer/>
      </div>
  
  );
}
